workflows:
  android-apk:
    name: Fatateer APK
    environment:
      java: 17

    scripts:
      - name: Build Debug APK
        script: |
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/*.apk
